In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import StandardScaler

In [4]:
columns = ['user_id', 'movie_id', 'rating', 'timestamp']

df = pd.read_csv(r"C:\Users\Welcome\Downloads\archive (3)\ml-latest-small\movies.csv", sep='\t', names=columns)

df.head()

,user_id,movie_id,rating,timestamp
0,"movieId,title,genres",NaN,NaN,NaN
1,"1,Toy Story (1995),Adventure|Animation|Childre...",NaN,NaN,NaN
2,"2,Jumanji (1995),Adventure|Children|Fantasy",NaN,NaN,NaN
3,"3,Grumpier Old Men (1995),Comedy|Romance",NaN,NaN,NaN
4,"4,Waiting to Exhale (1995),Comedy|Drama|Romance",NaN,NaN,NaN

In [5]:
# Drop timestamp (not needed)
df = df.drop('timestamp', axis=1)

# Check dataset info
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9743 entries, 0 to 9742
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   9743 non-null   object
 1   movie_id  0 non-null      float64
 2   rating    0 non-null      float64
dtypes: float64(2), object(1)
memory usage: 228.5+ KB
None
       movie_id  rating
count       0.0     0.0
mean        NaN     NaN
std         NaN     NaN
min         NaN     NaN
25%         NaN     NaN
50%         NaN     NaN
75%         NaN     NaN
max         NaN     NaN

In [6]:
user_item_matrix = df.pivot(index='user_id', columns='movie_id', values='rating')

user_item_matrix.head()

movie_id                                            NaN
user_id
1,Toy Story (1995),Adventure|Animation|Children...  NaN
10,GoldenEye (1995),Action|Adventure|Thriller       NaN
100,City Hall (1996),Drama|Thriller                 NaN
100044,Human Planet (2011),Documentary              NaN
100068,Comme un chef (2012),Comedy                  NaN

In [7]:
# Mean centering
user_mean = user_item_matrix.mean(axis=1)

matrix_centered = user_item_matrix.sub(user_mean, axis=0)

# Fill NaN with 0 for SVD
matrix_centered = matrix_centered.fillna(0)

In [8]:
k = 20   # latent factors (can change later)

svd = TruncatedSVD(n_components=k, random_state=42)

U = svd.fit_transform(matrix_centered)
Sigma = svd.singular_values_
VT = svd.components_

ValueError: Found array with 1 feature(s) (shape=(9743, 1)) while a minimum of 2 is required by TruncatedSVD.